### ISSUE TITLE
Couldnot find the eval_clustering.py file

### ISSUE THREAD

**Issue by Gracesta** [gyfastas/HCSC#6]
Hello there and thanks for your great work!
I tried to reproduce the clustering evaluation with the code.
But I didn't find the eval_clustering.py file to run.
Could I ask where to get the eval_clustering.py file?

Thank you

**Comment by gyfastas** [comment]
Hi! You can use the evaluation script in our new work HIRL: 
https://github.com/hirl-team/HIRL/blob/main/eval_common/eval_clustering.py.

----- 原始邮件 -----
发件人: "Yang" ***@***.***>
收件人: "hirl-team/HCSC" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期二, 2022年 9 月 06日 下午 6:02:42
主题: [hirl-team/HCSC] Couldnot find eval_clustering.py file (Issue #6)

Hello there and thanks for your great work!
I tried to reproduce the clustering evaluation with the code.
But I didn't find the eval_clustering.py file to run.
Could I ask where to get the eval_clustering.py file?

Thank you

-- 
Reply to this email directly or view it on GitHub:
https://github.com/hirl-team/HCSC/issues/6

**Comment by Gracesta** [comment]
Thanks for your kindness!
May I ask another question?
I just wanna tried clustering evaluation on my MacBook, with CPU.
When I ran the given script, message "Does not support training without GPU." was returned.
I'm just wondering whether I can try clustering evaluation with GPU.

Thank you so much!

**Comment by gyfastas** [comment]
Hi! The clustering evaluation without GPU might be very slow. You can check if the installed faiss library is cpu version. Probably you need to install the cpu version.

----- 原始邮件 -----
发件人: "Yang" ***@***.***>
收件人: "hirl-team/HCSC" ***@***.***>
抄送: "gyfastas" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期三, 2022年 9 月 07日 上午 9:33:06
主题: Re: [hirl-team/HCSC] Couldnot find the eval_clustering.py file (Issue #6)

Thanks for your kindness!
May I ask another question?
I just wanna tried clustering evaluation on my MacBook, with CPU.
When I ran the given script, message "Does not support training without GPU." was returned.
I'm just wondering whether I can try clustering evaluation with GPU.

Thank you so much!

**Comment by Gracesta** [comment]
Thanks for your reply!
I did install faiss-cpu library and run the script without errors or warnings.
But the program ended with "Does not support training without GPU" as below.

```
python3 eval_clustering.py --dist-url tcp://localhost:10001 \                         
--multiprocessing-distributed --world-size 1 --rank 0 \
--num-cluster 10 \                        
--pretrained checkpoints/hcsc_200eps.pth \
imagenette
Does not support training without GPU.
```

It seems like there is a restrict in code on running on CPU.
So I'm wondering if I could test with my CPU.
Thank you

**Comment by gyfastas** [comment]
Hi! I checked and found that it is raised from distributed initialization: https://github.com/hirl-team/HIRL/blob/1d36632f2df4ace4638af7f9f66e1ea35b1ed5c1/hirl/utils/dist.py#L7-L39; 
I think a direct solution is not using the distributed multiprocessing. Also, remember to cancel the `model.cuda()`.


----- 原始邮件 -----
发件人: "Yang" ***@***.***>
收件人: "hirl-team/HCSC" ***@***.***>
抄送: "gyfastas" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期三, 2022年 9 月 07日 上午 11:11:33
主题: Re: [hirl-team/HCSC] Couldnot find the eval_clustering.py file (Issue #6)

Thanks for your reply!
I did install faiss-cpu library and run the script without errors or warnings.
But the program ended with "Does not support training without GPU" as below.

```
python3 eval_clustering.py --dist-url tcp://localhost:10001 \                         
--multiprocessing-distributed --world-size 1 --rank 0 \
--num-cluster 10 \                        
--pretrained checkpoints/hcsc_200eps.pth \
imagenette
Does not support training without GPU.
```

It seems like there is a restrict in code on running on CPU.
So I'm wondering if I could test with my CPU.
Thank you

**Comment by Gracesta** [comment]
Hello and thanks for your patience!
Following your advice:

1.  I commented out 'model.cuda()'
2. And  commented out L8-L25 except "os.environ":
 https://github.com/hirl-team/HIRL/blob/1d36632f2df4ace4638af7f9f66e1ea35b1ed5c1/hirl/utils/dist.py#L8-L25;

But got another error shown below and wondering if I can get a help:
```
Traceback (most recent call last):
  File "/Users/HCSC/eval_clustering.py", line 192, in <module>
    val_results = run(args)
  File "/Users/HCSC/eval_clustering.py", line 156, in run
    load_pretrained_weights(model, args.pretrained, args.backbone_prefix, args.model_prefix)
  File "/Users/HCSC/eval_clustering.py", line 130, in load_pretrained_weights
    checkpoint_model = checkpoint[model_prefix]
```

PS. the given eval_clustering.py file is from other project (hirl) and seems there are some input inconsistent arguments with the script you gave in HCSC project. (e.g. rank->local_rank, world_size not exists but given in command )
I tried to add these arguments but not very sure I did right. Is there any chance that you could have a check that whether eval_clustering.py can be executed for clustering evaluation?

Thanks for your reply.

**Comment by BENLONGLONG2000** [comment]
Hello sir, have you been able to use eval_clustering?
